services:
  weather-station:
    build:
      context: ./web
    container_name: weather-station
    restart: unless-stopped

    ports:
      - "3000:3000"

    env_file:
      - ./web/.env

    volumes:
      - /var/lib/weather-station:/data